// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHc0FaOgMWx4MdshOIqd6RB5MC5HZ_86Q',
    appId: '1:448128087215:web:4505f5302aa73b6990505a',
    messagingSenderId: '448128087215',
    projectId: 'listin-flutter-firebase',
    authDomain: 'listin-flutter-firebase.firebaseapp.com',
    storageBucket: 'listin-flutter-firebase.firebasestorage.app',
    measurementId: 'G-RREQEBY9ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC533v4mc2Jss0moBoqyjOEmeQeAP4giWE',
    appId: '1:448128087215:android:1271900f4ff232b290505a',
    messagingSenderId: '448128087215',
    projectId: 'listin-flutter-firebase',
    storageBucket: 'listin-flutter-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA8XOrw3i4N5BTjlFa7k0jgBcQPdyucfM',
    appId: '1:448128087215:ios:f927f191c08256d190505a',
    messagingSenderId: '448128087215',
    projectId: 'listin-flutter-firebase',
    storageBucket: 'listin-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.example.listin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA8XOrw3i4N5BTjlFa7k0jgBcQPdyucfM',
    appId: '1:448128087215:ios:f927f191c08256d190505a',
    messagingSenderId: '448128087215',
    projectId: 'listin-flutter-firebase',
    storageBucket: 'listin-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.example.listin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHc0FaOgMWx4MdshOIqd6RB5MC5HZ_86Q',
    appId: '1:448128087215:web:76b32606fe87a73d90505a',
    messagingSenderId: '448128087215',
    projectId: 'listin-flutter-firebase',
    authDomain: 'listin-flutter-firebase.firebaseapp.com',
    storageBucket: 'listin-flutter-firebase.firebasestorage.app',
    measurementId: 'G-LESWK0RMM1',
  );

}